#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
cd frontend

SRC_PATTERN="^frontend/"
# NOTE: here we compare the current commit with the previous one (VZ)
if git diff @~..@  --name-only | grep --quiet "$SRC_PATTERN"
then
  pnpm run lint && pnpm run unused-exports && pnpm build
else
  exit 0
fi