#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
cd frontend

SRC_PATTERN="frontend/"

if git diff @{push} --cached --name-only | grep --quiet "$SRC_PATTERN"
then
  pnpm run lint && pnpm run unused-exports && pnpm build
else
  exit 0
fi