export type TIcons =
  | 'abc'
  | 'ac-unit'
  | 'access-alarm'
  | 'close'
  | 'search'
  | 'download'
  | 'edit'
  | 'expand-less'
  | 'expand-more'
  | 'more-vertical'
  | 'more-horizontal'
  | 'visibility'
  | 'delete'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'arrow-right-alt'
  | 'add'
  | 'insert-drive-file'
  | 'badge'
  | 'people'
  | 'people-alt'
  | 'nature-people'
  | 'computer'
  | 'connect-without-contact'
  | 'policy'
  | 'menu-book'
  | 'settings'
  | 'undo'
  | 'redo';

// TODO: Add more types of icons (YD)
