TRUNCATE TABLE EMPLOYEE_POSITION CASCADE;
TRUNCATE TABLE LOCATION CASCADE;
TRUNCATE TABLE ASSET CASCADE;
TRUNCATE TABLE ASSET_TYPE CASCADE;
TRUNCATE TABLE EMPLOYEE CASCADE;
TRUNCATE TABLE ASSET_REQUEST CASCADE;
TRUNCATE TABLE LEAVE_REQUEST CASCADE;
TRUNCATE TABLE VACANCY CASCADE;
