server:
  port: "8080"
spring:
  application:
    name: "audra-service"
  datasource:
    url: "jdbc:postgresql://localhost:5432/audra"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"

  jpa:
    open-in-view: false
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        enable-lazy-load-no-trans: false
  liquibase:
    #    enabled: false
    change-log: "classpath:/db/changelog/changelog-master.xml"
    database-change-log-lock-table: "DATABASECHANGELOGLOCK"
    database-change-log-table: "DATABASECHANGELOG"
    default-schema: "public"
    url: "jdbc:postgresql://localhost:5432/audra"
    user: "postgres"
    password: "postgres"
    contexts: "local"
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      port: 27017
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}
      gridfs.database: files

management:
  server:
    port: "8081"
    address: "127.0.0.1"
  endpoints:
    web:
      base-path:
      path-mapping:
        health: "/healthz"
        info: "/infoz"
        prometheus: "/prometheus"
      exposure:
        include: "health,info,prometheus"

logging:
  level:
    liquibase: "INFO"
    org:
      springframework:
        web: "info"

graphql:
  servlet:
    mapping: "/graphql"
    enabled: true
    corsEnabled: false

graphiql:
  mapping: "/graphiql"
  endpoint:
    graphql: "/graphql"
  static:
    basePath: "/"
  enabled: "true"
  pageTitle: "GraphiQL"
  cdn:
    enabled: "true"
    version: "0.17.5"
  props:
    variables:
      editorTheme: "solarized light"

storage.destination.url: http://localhost:8080/resources

resource:
  thumbnail:
    height: 800
    width: 500
